### ISSUE TITLE
求指导

### ISSUE THREAD

**Issue by huanghe2015** [max2max/freess#1]
大神，我在Conoha购买了VPS，安装了Shadowsocks服务器（服务器操作系统是Ubuntu）。但怎么弄就是弄不好，防火墙都配过了，还是搞不定，求协助（现在一直用你的，挺不好意思的，想自己做一个，但遇到麻烦了）。
Google Hangouts：2524737581@qq.com
QQ：2524737581（小号）
还有TeamViewer等等，实在不行可以私信把我的账号发给你。

**Comment by max2max** [comment]
有telegram账号吗

**Comment by huanghe2015** [comment]
刚刚试了，Telegram好像不支持IPv6，恐怕有难度（这种就尽量不走您的服务器了）。

**Comment by max2max** [comment]
电脑上ping和tcping来一发测试
另外你是用ipv6校园网？
不必敬语

**Comment by max2max** [comment]
如果是ipv6，把ipv6的防火墙也打开，另外请问你用的是哪个教程

**Comment by huanghe2015** [comment]
SSH正常，IPv6校园网对滴，ping和tcping都失败了，防火墙参考ufw，Shadowsocks服务器用的是“秋水逸冰”的一键脚本：https://teddysun.com/342.html

**Comment by max2max** [comment]
ping和tcping走的是ipv6吗

**Comment by max2max** [comment]
直接把防火墙关了，再测ping

**Comment by max2max** [comment]
另外建议试试besttrace查看路由

**Comment by huanghe2015** [comment]
Telegram：AK88103

**Comment by max2max** [comment]
tg已联系
