### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by hoodiearon** [max2max/freess#6]
我们的repo其实是差不多的，你的比我做的还早一些；我们可以共享一些站点（猜测：可能我们都做过只是没有明说），这样可以减轻些工作量，虽然我现在也没什么要在这方面做的了，毕竟早就没有以前的心气了，我也想过几次删库，但还是算了...；墙的等级略有不同，有的污染，论坛的cdn那ip已经被封了，基于这些，倒是有些建议：

* 添加一些网页代理网站 （防封ip）
* Simple DNSCrypt 的下载连接 （防止DNS投毒用的）
* Alvin9999的连接可以去掉，他的链接有些不良的目的
* SSRSHARE论坛的话，我觉得你更新镜像站点就好了 （源站点跟封ip基本差不多了...）
* 白漂机场有些需要注册才能用，多加入些开放几个免费节点的机场（随意吧）

说了这么多，意思就是合作分享下及对你的repo增加几个跳板链接改进的建议

**Comment by max2max** [comment]
感谢回复
找白嫖机场废时间
更新镜像费时间
DNScrypt我自己从来不用，懒得花时间研究
网页代理费时间

除非有人提供现成的

再次感谢！

**Comment by loremwalker** [comment]
已加入致谢名单
![](https://p3.cdn.img9.top/ipfs/QmUMoC2f687PsKtHe9HpbjxidgE13WtEFxugR5mrLyhi6Y?3.png)

**Comment by huwei365** [comment]
Alvin9999的链接我也觉得应该去掉, 今天点击去一看原来是轮子们维护的, 借着翻墙来宣扬那些脑残的东西.
